/*
 * File: app/view/FinishPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DigitialPassport.view.FinishPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.finishpanel',

    requires: [
        'Ext.Panel',
        'Ext.carousel.Carousel'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 9,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        flex: 10,
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'container',
                                flex: 5,
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'carousel',
                                        flex: 10,
                                        items: [
                                            {
                                                xtype: 'panel'
                                            },
                                            {
                                                xtype: 'panel'
                                            },
                                            {
                                                xtype: 'panel'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 5
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                layout: 'hbox'
            }
        ]
    }

});