/*
 * File: app/view/ProcessPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DigitialPassport.view.ProcessPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.processpanel',

    requires: [
        'Ext.Container',
        'Ext.Button'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton1',
                        text: 'bacl'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton2',
                        text: 'next'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 8
            },
            {
                xtype: 'container',
                flex: 1
            }
        ]
    }

});