/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DigitialPassport.controller.MainController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.maincontroller',

    config: {
        control: {
            "button#mybutton1": {
                tap: 'onMybutton1Tap'
            },
            "button#mybutton": {
                tap: 'onMybuttonTap'
            },
            "button#mybutton2": {
                tap: 'onMybutton2Tap'
            }
        }
    },

    onMybutton1Tap: function(button, e, eOpts) {
         Ext.Viewport.animateActiveItem({xtype:'startpanel'},{type: 'slide', direction: 'right'});
    },

    onMybuttonTap: function(button, e, eOpts) {
        Ext.Viewport.animateActiveItem({xtype:'processpanel'},{type: 'slide', direction: 'left'});
    },

    onMybutton2Tap: function(button, e, eOpts) {
        Ext.Viewport.animateActiveItem({xtype:'finishpanel'},{type: 'slide', direction: 'left'});
    }

});